#if !defined(AFX_RBGAUGE_H__BB02C9B1_6A81_11D3_9870_0080C83832F8__INCLUDED_)
#define AFX_RBGAUGE_H__BB02C9B1_6A81_11D3_9870_0080C83832F8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CRBGauge wrapper class

class CRBGauge : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRBGauge)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x32c38c43, 0x6a6b, 0x11d0, { 0xa7, 0x4c, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AboutBox();
	double GetValue();
	void SetValue(double newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH newValue);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH newValue);
	void SetRefPicture(LPDISPATCH newValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetHWnd();
	float GetCaptionHeight();
	double GetValueMinimum();
	void SetValueMinimum(double newValue);
	double GetValueMaximum();
	void SetValueMaximum(double newValue);
	float GetOriginLeft();
	void SetOriginLeft(float newValue);
	float GetOriginTop();
	void SetOriginTop(float newValue);
	float GetRadius();
	void SetRadius(float newValue);
	short GetLineWidth();
	void SetLineWidth(short nNewValue);
	float GetAngleMinimum();
	void SetAngleMinimum(float newValue);
	float GetAngleMaximum();
	void SetAngleMaximum(float newValue);
	BOOL GetClockwise();
	void SetClockwise(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RBGAUGE_H__BB02C9B1_6A81_11D3_9870_0080C83832F8__INCLUDED_)
