//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FreeScan.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDS_TITLE                       102
#define IDS_VERSION                     103
#define IDR_MAINFRAME                   128
#define IDD_ABOUT                       129
#define IDD_DETAIL                      130
#define IDD_STATUS                      131
#define IDC_TIME                        132
#define IDD_RAWHEX_0                    133
#define IDD_ENGINEDATA                  134
#define IDB_LOGO                        135
#define IDD_TCODES                      136
#define IDD_RAWHEX_1                    137
#define IDB_BADGE                       138
#define IDB_BANNER                      139
#define IDD_SENSORS                     140
#define IDD_ADVANCED                    141
#define IDD_DASHBOARD                   142
#define IDD_DESIDLE                     144
#define IDD_DIALOG1                     146
#define IDD_ENGINEVIEW                  150
#define IDB_LEDS                        152
#define IDD_STATUSBITS                  153
#define IDC_STATUS                      1003
#define IDC_STARTLOG                    1004
#define IDC_TEST1                       1005
#define IDC_TEST2                       1008
#define IDC_START                       1009
#define IDC_STOP                        1010
#define IDC_ABOUTVERSION                1018
#define IDC_COMSELECT                   1019
#define IDC_HIDE                        1020
#define IDC_LISTEN                      1079
#define IDC_INTERACT                    1080
#define IDC_ENUMERATE                   1081
#define IDC_DELAY                       1082
#define IDC_TLIST                       1094
#define IDC_SENT                        1096
#define IDC_RECEIVED                    1097
#define IDC_LOGO                        1098
#define IDC_CSV                         1099
#define IDC_CSVOPTIONS                  1100
#define IDC_TACHO                       1101
#define IDC_SPEEDO                      1102
#define IDC_RBGAUGE3                    1103
#define IDC_VOLT                        1104
#define IDC_WATER                       1106
#define IDC_RPM                         1107
#define IDC_MPH                         1108
#define IDC_COOLANT                     1109
#define IDC_BOOST                       1110
#define IDC_COOLANTVOTS                 1110
#define IDC_THROTTLEPOS                 1111
#define IDC_RUNTIME                     1112
#define IDC_THROTTLEVOLTS               1112
#define IDC_BATVOLTS                    1113
#define IDC_THROTTLEADC                 1113
#define IDC_EPROMID                     1114
#define IDC_COOLANTADC                  1114
#define IDC_STATUS6                     1115
#define IDC_STATUS7                     1116
#define IDC_SPARKADV                    1117
#define IDC_KNOCK                       1118
#define IDC_O2VOLTS                     1119
#define IDC_KNOCKCOUNT                  1119
#define IDC_THROTLOAD                   1120
#define IDC_O2VOLTSR                    1120
#define IDC_DESIDLE                     1121
#define IDC_CRANK                       1122
#define IDC_STATUS2                     1123
#define IDC_STATUS0                     1124
#define IDC_ENGINELOAD                  1125
#define IDC_IAC                         1126
#define IDC_MAT                         1127
#define IDC_BARO                        1128
#define IDC_MATVOLTS                    1128
#define IDC_STARTCOOLANT                1129
#define IDC_MAP                         1129
#define IDC_AIRFUEL                     1130
#define IDC_MAPVOLTS                    1130
#define IDC_BAROMETER                   1131
#define IDC_AIRFLOW                     1131
#define IDC_BAROVOLTS                   1132
#define IDC_INTR                        1132
#define IDC_RLCOUNTL                    1133
#define IDC_MATADC                      1133
#define IDC_RLCOUNTR                    1134
#define IDC_MAPADC                      1134
#define IDC_BAROADC                     1135
#define IDC_BLM                         1135
#define IDC_BLM_NUMBER                  1136
#define IDS_DTC12                       1229
#define IDS_DTC13                       1230
#define IDS_DTC14                       1231
#define IDS_DTC15                       1232
#define IDS_DTC21                       1233
#define IDS_DTC22                       1234
#define IDS_DTC23                       1235
#define IDS_DTC24                       1236
#define IDS_DTC25                       1237
#define IDS_DTC26                       1238
#define IDS_DTC31                       1239
#define IDS_DTC33                       1240
#define IDS_DTC34                       1241
#define IDS_DTC35                       1242
#define IDS_DTC41                       1243
#define IDS_DTC42                       1244
#define IDS_DTC43                       1245
#define IDS_DTC44                       1246
#define IDS_DTC45                       1247
#define IDS_DTC51                       1248
#define IDS_DTC53                       1249
#define IDS_DTC65                       1250
#define IDC_DTC1                        1283
#define IDC_DTC2                        1284
#define IDC_DTC3                        1285
#define IDC_RESETDTC                    1286
#define IDC_SEND                        1287
#define IDC_05_DB00                     1306
#define IDC_05_DB01                     1307
#define IDC_05_DB02                     1308
#define IDC_05_DB03                     1309
#define IDC_05_DB04                     1310
#define IDC_05_DB05                     1311
#define IDC_05_DB06                     1312
#define IDC_05_DB07                     1313
#define IDC_05_DB08                     1314
#define IDC_05_DB09                     1315
#define IDC_0A_DB00                     1316
#define IDC_0A_DB01                     1317
#define IDC_0A_DB02                     1318
#define IDC_DB00                        1423
#define IDC_DB01                        1432
#define IDC_DB02                        1441
#define IDC_DB03                        1450
#define IDC_DB04                        1459
#define IDC_DB05                        1468
#define IDC_DB06                        1477
#define IDC_DB07                        1478
#define IDC_SETDESIDLE                  1480
#define IDC_VALUE                       1481
#define IDC_SPIN                        1482
#define IDC_RESETBLM                    1483
#define IDC_RESETIAC                    1484
#define IDC_RBGABOUT                    1487
#define IDC_RBGAUGE1                    1488
#define IDC_THROT                       1489
#define IDC_MODEL                       1491
#define IDC_COMMENTS                    1494
#define IDC_DISPLAY_STATIC              1495
#define IDC_O2VOLTSL                    1496
#define IDC_FORCE                       1497
#define IDC_INTL                        1497
#define IDC_SPARK                       1498
#define IDC_INT                         1498
#define IDC_HYPERLINK                   1499
#define IDC_RLCOUNT                     1499
#define IDC_HYPERLINK1                  1499
#define IDC_OILTEMP                     1500
#define IDC_HYPERLINK2                  1500
#define IDS_KNOCKCOUNT                  1501
#define IDC_VIEW                        1501
#define IDC_TEST                        1502
#define IDC_DEGC                        1505
#define IDC_DEGF                        1506
#define IDC_KPH                         1508
#define IDC_LED1                        1508
#define IDC_ON                          1509
#define IDC_OFF                         1510
#define IDC_DISABLE                     1511
#define IDC_LED2                        1512
#define IDC_LED3                        1513

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1515
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
